### ISSUE TITLE
No highlighting so far ?!

### ISSUE THREAD

**Issue by snoopje** [Frogli/OmnisStudioHighlighter#3]
Hi Frogli,
just installed the OMNIS HL, something I was waiting for a long time ! Thanks for sharing that !

after Installation and choosing the OMNIS syntax I could not see any effect ?!

Any hint ?
<img width="874" alt="bildschirmfoto 2017-11-01 um 10 32 16" src="https://user-images.githubusercontent.com/1171632/32268571-f662f7c6-beef-11e7-9f7a-547c02c1e697.png">

**Comment by Frogli** [comment]
Hi Snoopje

Which installation method did you use? If it was the Package Control method I suggest to try the manual one for now. I saw that Package Control had a old version which had some YAML syntax errors. I have double check the manual installation and that should still work. Further I have created a new tag on the repository in order to get a new version (1.1.3) in the Package Control system.

**Comment by Frogli** [comment]
While I was writing the above version 1.1.2 was published by PackageControl.io and should also be working.

**Comment by snoopje** [comment]
THX, I did it the manual way and that works !
